### ISSUE TITLE
Bug, drop event on Flutter Dropzone Web

### ISSUE THREAD

**Issue by souzantero** [deakjahn/flutter_dropzone#1]
With more than one `DropzoneView` widget the `_onDrop` method in `FlutterDropzoneView` class only trigger the latest `viewId`.

**Comment by deakjahn** [comment]
@souzantero Before I look into it, could you check it out the that "final initial version" (1.0.2) works for you when referenced normally from pub.dev?

**Comment by deakjahn** [comment]
OK, fixed. Although the Dart side instantiated as many views as you wanted, the JS side only had one handler... :-)

Please, test it.

**Comment by souzantero** [comment]
> @souzantero Before I look into it, could you check out whether the "final initial version" (1.0.2) works for you when referenced normally from pub.dev?

Hi, work for me. Thanks!

**Comment by souzantero** [comment]
I test it after fix and worked
