### ISSUE TITLE
How do I get a callback from DropzoneViewController.pickFiles() ?

### ISSUE THREAD

**Issue by rednikisfun** [deakjahn/flutter_dropzone#10]
I want to implement a Dropzone as well as a button to pick a file from, I am using DropzoneViewController.pickFiles() to achieve picking files, but in order to get any information about the file I need an HTML file, but there is none coming from DropzoneViewController.pickFiles().

**Comment by rednikisfun** [comment]
Closing this because I found out that the callback of the function DropzoneViewController.pickFiles() itself is a list of files.

**Comment by deakjahn** [comment]
Yes. I added a line to README to make this more obvious.

**Comment by rednikisfun** [comment]
Another question I had was if it is possible to check the format of the file?

**Comment by deakjahn** [comment]
Use `getFileMIME()`.
