### ISSUE TITLE
onLoaded never being called

### ISSUE THREAD

**Issue by jackforesightmobile** [deakjahn/flutter_dropzone#13]
Hi, I am trying to implement this plugin but having issues with getting anything working. I am using the DropzoneView from the example. onCreated is called, but onLoaded is never called and whenever I drag a file into the dropzone it just opens the file in a new tab and onDrop is not called at this point either.

I'm not really sure where to go from here, I get no error output in the flutter console or the javascript web console.

Maybe I am missing something, this is my DropzoneView:

```
    return Container(
      height: 200,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(8.0),
      ),
      child: Stack(
        children: [
          DropzoneView(
            operation: DragOperation.copy,
            cursor: CursorType.grab,
            onCreated: (ctrl) {
              _dropzoneViewController = ctrl;
              print("Controller init");
            },
            onLoaded: () => print('Zone 1 loaded'),
            onError: (ev) => print('Zone 1 error: $ev'),
            onHover: () {
              print('Zone 1 hovered');
            },
            onLeave: () {
              print('Zone 1 left');
            },
            onDrop: (ev) {
              print('Zone 1 drop: ${ev.name}');
            },
          ),
          Center(
            child: Text("Drag and drop"),
          )
        ],
      ),
    );
```

Thanks in advance for any help!

**Comment by deakjahn** [comment]
There was a very recent change (yesterday and today) about how the zone is initialized (there was nothing fundamentally wrong with the earlier approach but some stricter content security policies didn't like it). I wonder it the new approach doesn't work for you for some case. Could you just download the whole package, simply unpack the zip, open it up in the IDE of your choice and run the example? What happens.

Yes, if there's no "loaded" message, the drop will not function, that's clear. But you should have a "loaded" message all right.

**Comment by jackforesightmobile** [comment]
Hi deakjahn, I just tried that and it worked fine, so I guess it's something I'm doing wrong or an issue with my project. Do you have any idea what could be causing the issue my end where the onCreated callback is called but the onLoaded isn't?

**Comment by deakjahn** [comment]
What are the exact circumstances? I mean: debug, release or profile? Running from Flutter directly (console or from the IDE) or uploading to the web and trying from a site? If the first, it's probably running in Chrome, but maybe in the second case? The new approach relies on CSS-based animations but that seems to be supported across the board: https://caniuse.com/css-animation

(Yes, I know "animation" sounds strange here but see this thread:  https://github.com/deakjahn/flutter_dropzone/issues/12)

**Comment by jackforesightmobile** [comment]
I'm running in debug in Chrome from IntelliJ

**Comment by deakjahn** [comment]
I would put a breakpoint on the `animationstart` listener, here:

https://github.com/deakjahn/flutter_dropzone/blob/19e1e5ec10fb5fd67569d4c6aa40bd625edaeffe/flutter_dropzone_web/lib/flutter_dropzone_web.dart#L27

to see if it's called at all. Also, check whether the attached internal style is in your DOM (use the Chrome debug tool, there will be a `<head>` with many items inside, and look around just at the end). Here they are from the example:

![Screenshot 2020-10-27 155328](https://user-images.githubusercontent.com/2234271/97319009-c07ec480-186c-11eb-9718-7f79d0ab9f1b.png)
![Screenshot 2020-10-27 155415](https://user-images.githubusercontent.com/2234271/97319019-c2e11e80-186c-11eb-8965-22b99f88c025.png)

If the dropzones don't have the animation, or the handler isn't attached or the style isn't there, that might be the reason.

**Comment by jackforesightmobile** [comment]
So the handler is attached and the div with the dropzone info is there.
![image](https://user-images.githubusercontent.com/47739475/97320540-d046da80-1865-11eb-9ddc-a14e82a64e10.png)
![image](https://user-images.githubusercontent.com/47739475/97320784-13a14900-1866-11eb-9063-30571d0d6920.png)

The _nativeCreate breakpoint is never hit. When I put a breakpoint on `container = DivElement()` it hits that breakpoint, but just never hits the _nativeCreate inside the 'animationstart' event listener.

**Comment by deakjahn** [comment]
Oh yes, I forgot to mention, the ones I showed were in CanvasKit (I only use that engine these days). `shadow-root` is with DomCanvas. But both should equally work.

Nope, it does not, neither for me now. Strange. Which engine did you try the example with?

**Comment by deakjahn** [comment]
@CrisNegoianu I'm starting to think that the "pretty darn sick trick" won't work across the shadow root. :-(

**Comment by jackforesightmobile** [comment]
On the example it's using the shadow-root too

**Comment by jackforesightmobile** [comment]
One thing that's strange is that in the working example the div doesn't have the same styling:
![Uploading image.png…]()

**Comment by deakjahn** [comment]
You can easily try CanvasKit by adding `--dart-define=FLUTTER_WEB_USE_SKIA=true` to your command line.

**Comment by jackforesightmobile** [comment]
Yep that worked!

**Comment by deakjahn** [comment]
That's still strange. The even doesn't need to pass from shadow to light. The handler is attached to the `div` inside the shadow.

**Comment by deakjahn** [comment]
OK. The handler is there but the `div` inside the shadow can't see the outer style. Try adding

    if (!const bool.fromEnvironment('FLUTTER_WEB_USE_SKIA', defaultValue: false))
      container.append(
        StyleElement()..innerText = '@keyframes dropzoneReady {from { clip: rect(1px, auto, auto, auto); } to { clip: rect(0px, auto, auto, auto); }}',
      );

to the end of the `FlutterDropzoneView()` constructor (I'll upload it here now but I'll only publish to dev if we're satisfied with it).

**Comment by vidklopcic** [comment]
The fix did solve the issue, but caused duplicate callbacks for all events. For some reason the `animationstart` event was firing more than once (from one to 4 times). This did solve the issue, however I have no idea why the callback fires more than once.
```Dart
EventListener listener;
listener = (event) {
  container.removeEventListener('animationstart', listener);
  _nativeCreate(
    container,
    allowInterop(_onLoaded),
    allowInterop(_onError),
    allowInterop(_onHover),
    allowInterop(_onDrop),
    allowInterop(_onLeave),
  );
  if (mime != null) setMIME(mime);
  if (operation != null) setOperation(operation);
  if (cursor != null) setCursor(cursor);
};
container.addEventListener('animationstart', listener);
```

**Comment by deakjahn** [comment]
Does this mean that the callback in the `main.dart` (the "loaded" one) appears more than once? It doesn't for me, so this is something we would need to reproduce.

**Comment by deakjahn** [comment]
@vidklopcic I pushed the current one to Pub to be at least partially OK but could you reply back whether you continue to see this? I can't reproduce this.

**Comment by CrisNegoianu** [comment]
Hey guys.
It is now working in release with CSP as well. I'm grateful for your efforts.

There is still this strange thing happening with all events being raised twice. Loaded, as well so file drop, for example.
Which must mean that the listener is being registered twice.
Funny thing is, it doesn't happen in while debugging, only in release.
I can work around it in release mode, not a problem. I can just check if the file is already in the list and ignore it the second time.

But you're definitely on the right track here.

**Comment by deakjahn** [comment]
Still only with your app or maybe with the example as well?

**Comment by CrisNegoianu** [comment]
On my app.
I haven't tried the example.
But I can't say that I've done something special. 
I've just copied the example.

**Comment by deakjahn** [comment]
If you could just try once because I've just did once more and nothing at my end...

**Comment by CrisNegoianu** [comment]
I'm out and about at the moment.
I'll try later and let you know.

**Comment by vidklopcic** [comment]
Yes, with current changes I still get duplicate entries. I added a `<script>` element that dispatches custom event when attached to DOM. This solved all issues for my use case. If you think the solution is ok, you can accept this pull request: [https://github.com/deakjahn/flutter_dropzone/pull/15](https://github.com/deakjahn/flutter_dropzone/pull/15)

**Comment by venkatd** [comment]
I'm having the same issue. It looks like the onDrop event keeps getting attached for some reason. So if I drag a file, then another, then another, I suddenly have ~5-6 duplicate events getting fired.

I also find that `onHover` gets triggered a very high number of times rather than the first time a hover event is fired.

I haven't been able to get to the bottom of the cause but I'm happy to jump on a screen-share to troubleshoot the issue.

**Comment by agreensh** [comment]
This package doesn't work at all for me (Flutter (Channel dev, 2.1.0-10.0.pre, on macOS 11.2.3 20D91 darwin-arm, locale en-GB). Running the example, no debug is produced at all - no onCreated, no onError, no onHover etc, nothing at all.

**Comment by venkatd** [comment]
@agreensh this library only current supports the web platform. For web, I ended up using a different library and modifying some of the source code. (At the moment, original library had some edge cases as well so I fixed those in my own version.) We haven't had any issues recently.

https://github.com/Derrick56007/dropzone/issues/2#issuecomment-796455029

Perhaps it can be tried out on this library.

**Comment by deakjahn** [comment]
@venkatd We started to discuss it at https://github.com/deakjahn/flutter_dropzone/issues/24. I can't yet reproduce it at my end. It should be debugged in the browser to see why it isn't firing.
