### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by 7sedam7** [deakjahn/flutter_dropzone#14]
Hi,

I have tried to use your plugin without success. When I try to drop a file into the area in the browser, the file just gets opened in a different tab. The same thing works fine in services like messenger/google drive/etc, so it's not a browser problem.

I have also tried to run your example without success.

I'm using manjaro, and chromium and running the project with `flutter run -d chrome`.

Is there anything I'm missing?

Cheers,
Joel

**Comment by deakjahn** [comment]
Please, check out https://github.com/deakjahn/flutter_dropzone/issues/13 and https://github.com/deakjahn/flutter_dropzone/issues/12. The changes are very recent, not yet on Dev. If they work for you, too, I'll push it to Dev.

**Comment by 7sedam7** [comment]
Thank you, works fine with `--dart-define=FLUTTER_WEB_USE_SKIA=true`

**Comment by deakjahn** [comment]
I can push the new to Pub and then it will work with `false` as well.
