### ISSUE TITLE
About multiple upload

### ISSUE THREAD

**Issue by DiMiTriFrog** [deakjahn/flutter_dropzone#16]
Is there a way to use DropZone to upload multiple files efficiently? It currently takes a long time.

One more thing, what are the "operation" and "cursor" options for?

**Comment by deakjahn** [comment]
To determine what kind of cursor you can see when hovering or dragging an item.

The module can only provide what HTML and the browser actually offer: see https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API
