### ISSUE TITLE
[Feature request] Highlighting background when file is being dragged over the zone

### ISSUE THREAD

**Issue by orestesgaolin** [deakjahn/flutter_dropzone#2]
I would like to be able to detect and highlight the DropzoneView when file is being dragged over the zone.
Either callback `onHover` or property e.g. `highlightOnHover` would be something great.

**Comment by deakjahn** [comment]
That didn't look that complicated. :-)

**Comment by orestesgaolin** [comment]
Would it be also possible to get callback when the mouse leaves the dropzone?

**Comment by orestesgaolin** [comment]
I solved my issue by this simple trick:

```dart
  void _onHover() {
    _highlighted = true;
    _highlightCheck = DateTime.now().millisecondsSinceEpoch;
    setState(() {});
    Future.delayed(Duration(milliseconds: 100)).then((value) {
      if (DateTime.now().millisecondsSinceEpoch - _highlightCheck > 99) {
        _highlighted = false;
        setState(() {});
      }
    });
  }
```

**Comment by deakjahn** [comment]
There is a `dragleave`: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API

**Comment by deakjahn** [comment]
Committed ce28623, but GitHub doesn't mark two commits for one issue automatically.

**Comment by deakjahn** [comment]
@orestesgaolin By the way, is this new event OK in your experience?

**Comment by deakjahn** [comment]
@orestesgaolin Dominik, shall we close this? Thanks.

**Comment by orestesgaolin** [comment]
It's working fine!

**Comment by deakjahn** [comment]
OK, thanks.
