### ISSUE TITLE
Package documentation says 'not' web

### ISSUE THREAD

**Issue by martinokeefe** [deakjahn/flutter_dropzone#21]
Bold highlighting added below.

"It's a federated plugin, meaning that it will compile in cross platform apps that contain both **Android/iOS** and **Web code**. It will **not function** on the **latter**"

This says it will not function in flutter Web apps. Changing latter to former will resolve.

['flutter_dropzone pub.dev'](https://pub.dev/packages/flutter_dropzone)

**Comment by deakjahn** [comment]
This has been change quite some time ago (see https://github.com/deakjahn/flutter_dropzone/blob/master/flutter_dropzone/README.md) and now I don't know where the wrong version still comes from...

**Comment by martinokeefe** [comment]
[Fixed applied 6th Nov]([url](https://github.com/deakjahn/flutter_dropzone/commit/7e87c5e6c6a8688da3fc6d95fd6c9d42b241aabe#diff-bf0f61f669d9eac7903e049a1324b57275a8289b5ce0928140871df3234c757a)). Last published to pub.dev previous Aug?

**Comment by deakjahn** [comment]
Thanks, good catch. I probably wanted to fix something else then forgot to publish in the end.

**Comment by martinokeefe** [comment]
Exactly the spirit of my post :-)
