### ISSUE TITLE
Example support..

### ISSUE THREAD

**Issue by Patrick386** [deakjahn/flutter_dropzone#22]
The Flutter_dropzone package works just fine with ease.
But I don't know how to read and save the file.
Can you make an example to utilize this package?
For example, it shows a list of files such as image files and excel, and uploads them to the Firebase cloud server.

**Comment by deakjahn** [comment]
Sorry, Patrick, I don't think that will happen. First, I don't use Firebase myself and I don't think such specific an example should be the task of a general plugin like this. Second, I think the current README already answers your question: you can call `getFileData()` of the controller to get the contents of the file as a byte array. This is the only access provided by the browser to the file, so don't expect regular Dart file operations (this is also mentioned there). You read the file contents with this function and the rest you need to look up in the Firebase docs.

Having said that, simply saving it locally is as simple as the standard:

    await File(filename).writeAsBytes(await controller.getFileData(file));
