### ISSUE TITLE
Please help with what properties does ev have

### ISSUE THREAD

**Issue by arualana** [deakjahn/flutter_dropzone#26]
I am looking at the documentatios
```
DropzoneView(
  operation: DragOperation.copy,
  cursor: CursorType.grab,
  onCreated: (ctrl) => controller = ctrl,
  onLoaded: () => print('Zone loaded'),
  onError: (ev) => print('Error: $ev'),
  onHover: () => print('Zone hovered'),
  onDrop: (ev) => print('Drop: $ev'),
  onLeave: () => print('Zone left'),
);
```

I need to know how to convert ev to PlatformFile

I don't know which properties ev has, please help

**Comment by deakjahn** [comment]
I added the types to the example. Regarding the file, please, go on reading the documentation. You cannot convert to PlatformFile, this is not possible in a browser. A Flutter Web app runs in a browser, so it can only do what the browser allows.

The [Using the controller](https://github.com/deakjahn/flutter_dropzone/blob/master/flutter_dropzone/README.md#using-the-controller) section describes how you can get the contents nd metadata of the file.

**Comment by arualana** [comment]
Thank you
