### ISSUE TITLE
[Bug] SyntaxError: Identifier 'FlutterDropzone' has already been declared

### ISSUE THREAD

**Issue by orestesgaolin** [deakjahn/flutter_dropzone#3]
After adding the DropZone and pressing CMD+S following error appears:

```
SyntaxError: Identifier 'FlutterDropzone' has already been declared
```

![image](https://user-images.githubusercontent.com/16854239/85332116-a0fb1800-b4d7-11ea-9b7f-a276c85de35c.png)

Sample code:

```
                DropzoneView(
                  operation: DragOperation.copy,
                  onCreated: (ctrl) => controller ??= ctrl,
                  onLoaded: () => logger.d('Zone loaded'),
                  onError: (ev) => logger.d('Error: $ev'),
                  onDrop: _onDrop,
                  onHover: _onHover,
                ),
```

Flutter 1.19.0-5.0.pre
Chrome 83.0.4103.106 on macOS

**Comment by deakjahn** [comment]
Apparently a kind of limitation (actually, a stricter syntax) introduced by [EcmaScript 6](https://stackoverflow.com/questions/49774769/javascript-uncaught-syntaxerror-identifier-has-already-been-declared). I'm not yet sure what could be done about it.

**Comment by deakjahn** [comment]
@orestesgaolin Please, check this. I'm aware of the _Bad state: Future already completed_ error, it seems to be a recurring Flutter error, annoying but harmful, cropping up quite often on hot reload in many scenarios.

**Comment by orestesgaolin** [comment]
Hey, thanks for letting me know. I used the current master and indeed the previous error is gone and now I see following:

![image](https://user-images.githubusercontent.com/16854239/85411053-28906780-b568-11ea-99db-1ab51082241a.png)

**Comment by deakjahn** [comment]
I can't seem to able to reproduce this. Debug or release? First run or reload?

**Comment by orestesgaolin** [comment]
```
    html.window.addEventListener('flutter_dropzone_web_ready', (_) {
      if (!_readyCompleter.isCompleted) _readyCompleter.complete(true);
    });
```

It appears to be the same error as yours. Checking for the completer seems to solve the issue

**Comment by deakjahn** [comment]
Oh, the bad future state? Then it might even be fixable, after all...? :-)

**Comment by orestesgaolin** [comment]
The callback was called three times in my case, I don't know why. I'm not sure if that's enough to fix but this simple change gets rid of the exception

**Comment by deakjahn** [comment]
You might be right. I saw this error in some many places with so many different plugins that I just accepted it as a Flutter problem and never actually checked it in detail.

**Comment by deakjahn** [comment]
The if it's really all right, I might just as well send it to Pub.
