### ISSUE TITLE
BackdropFilter is influenced by presence of DropzoneView

### ISSUE THREAD

**Issue by lrmoorejr** [deakjahn/flutter_dropzone#30]
I have a Row layout with a DropzoneView on the right side, and a translucent navigation panel using BackdropFilter with a blur on the left.  I've placed the DropzoneView in a Stack with a green container so it is clear there is no overlap:

```
Stack(
	children: [
		Container(color:const Color.fromARGB(128, 0, 128, 0)),
		if(kIsWeb) DropzoneView(
			operation: DragOperation.copy,
			cursor: CursorType.grab,
			onCreated: (dropzoneViewController) {
				
			},
			onLoaded: () => debugPrint('Zone loaded'),
			onError: (ev) => debugPrint('Error: $ev'),
			onHover: () => debugPrint('Zone hovered'),
			onDrop: (ev) => debugPrint('Drop: $ev'),
			onLeave: () => debugPrint('Zone left'),
		),
		const Center(child: Text('Drop files here')),
	],
)

```
Interestingly, the BackdropFilter on the left seems to pick up some white color, only when the DropzoneView is in the tree, even though they do not overlap.  If I draw the BackdropFilter before drawing the DropzoneView, there is no problem (and I guess that will need to be my workaround if a fix is problematic).

Here is the page with the DropzoneView:

![with_backdrop_filter](https://user-images.githubusercontent.com/53207771/132901328-1262bb48-8c51-40aa-bf2b-7c42e8a13397.png)

And here it is without.:

![Without_dropzoneview](https://user-images.githubusercontent.com/53207771/132902567-5fbd4871-46b1-406c-980a-d86a52cbc1d1.png)

I've confirmed that the same issue occurs on Firefox, as well.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.5.0-5.3.pre, on Ubuntu 21.04 5.11.0-31-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.2)
[✓] Android Studio
[✓] VS Code
[✓] Connected device (2 available)

• No issues found!

**Comment by deakjahn** [comment]
The width/height message is discussed in this [Flutter doc](https://flutter.dev/docs/release/breaking-changes/platform-views-using-html-slots-web) as a side effect, but it mainly deals with the changes in the HTML rendering. I wonder if the two are related. Actually, the good way to test this would be to create a minimalistic example, without dropzone, just the backdrop and an empty platform view. If that shows the rendering problem as well, this is something that should be reported to the Flutter Web team...

**Comment by lrmoorejr** [comment]
Confirmed that it is a flutter web issue.

https://github.com/flutter/flutter/issues/89889

Thanks!
