### ISSUE TITLE
Can't compile after flutter_dropzone_web update to 2.0.4 on Flutter 2.2

### ISSUE THREAD

**Issue by CLucera** [deakjahn/flutter_dropzone#31]
After the latest update of flutter_dropzone_web simply adding the flutter_dropzone: ^2.0.1 make the project not compilable anymore.

This issue is not happening on Flutter 2.5, but it is happening on flutter 2.3 and previous versions

## Error

```
../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_dropzone_web-2.0.4/lib/flutter_dropzone_plugin.dart:101:15: Error: No named parameter with the name 'onPlatformViewCreated'.
              onPlatformViewCreated: onPlatformViewCreated,
              ^^^^^^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/widgets/platform_view.dart:345:9: Context: Found this candidate, but the arguments don't match.
  const HtmlElementView({
        ^^^^^^^^^^^^^^^
Failed to compile application.
```

## How to reproduce

1. Create a new Flutter project
2. Open pubspec.yaml
3. Add ` flutter_dropzone: ^2.0.1` as dependency
4. Run the project.

## Flutter doctor log
```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.5.2 20G95 darwin-x64, locale
    it-IT)
    • Flutter version 2.2.1 at /Users/carlo/flutter
    • Framework revision 02c026b03c (4 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
```

## Current workaround
Add ` flutter_dropzone: 2.0.3` as dependency

**Comment by deakjahn** [comment]
Well, that's true but this was a long standing bug in Flutter that has been finally fixed... (https://github.com/flutter/flutter/issues/56181) I wouldn't really like to revert it. Is there any reason you don't want to upgrade Flutter now?

**Comment by goncalo-palma-3r** [comment]
@deakjahn I agree that it's a fix, however this can break current projects.

This change created a **breaking change** in a minor version increase, which means that now we cannot compile our application if dart pub tries to fetch the latest version.

All breaking changes should have their own major version change. And some info on the changelog as to why

**Comment by deakjahn** [comment]
Fair enough but I didn't expect it to be a breaking change. :-)

**Comment by deakjahn** [comment]
I have 2.0.5 now reverting the changes. Could you confirm that it works with 2.2 again?

I'll prepare the proper breaking change then.

**Comment by deakjahn** [comment]
@goncalo-palma-3r @CLucera I have the new 2.1 ready but I'll wait for you guys to be sure that the old one works again now. :-)

**Comment by carlo-lucera-3r** [comment]
Can confirm working on 2.3.0-0.1.pre, this can be closed, thank you @deakjahn!

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.3.0-0.1.pre, on Linux, locale en_US.UTF-8)

**Comment by goncalo-palma-3r** [comment]
Thank you for your kindness @deakjahn !

We really appreciate it

**Comment by amr-eniou-3r** [comment]
Thanks a lot

**Comment by deakjahn** [comment]
OK, thanks, then I'll go on with 2.1, let's see whether I do something wrong or not. :-)
