### ISSUE TITLE
[FeatureRequest] Could you please pass html.file object on onDrop function?

### ISSUE THREAD

**Issue by hayashi-tz** [deakjahn/flutter_dropzone#32]
Dear Developers,

If possible, could you please kindly pass html.file object at onDrop function? Because there has some freeze when we drop very large size when retrieving controller.getFileData(event). So, when the library can pass html.file, it is better to listen with html.FileReader with Chunk size.

Could you please kindly add this feature, I look forward appreciate your support.

Thank you very much.

**Comment by deakjahn** [comment]
It's an async operation to get the file, so I don't think so. Besides, if it takes too much time for you to do it yourself, it would take just as much time for the plugin. You'll need to use the usual async practices to make your UI reponsive enough, I'm afraid.
