### ISSUE TITLE
Not working in the web release build

### ISSUE THREAD

**Issue by a914-gowtham** [deakjahn/flutter_dropzone#34]
In debug build it work fine. but, when I run in release build using `flutter run --release` command the view just  is showing  grey 
color
![Screenshot from 2021-10-13 15-04-49](https://user-images.githubusercontent.com/68514286/137108287-9fa11037-0278-4023-be82-b6fe78228573.png)

**Comment by AndriiMatkivskyiSecurrency** [comment]
@a914-gowtham What was the issue?

**Comment by a914-gowtham** [comment]
@AndriiMatkivskyiSecurrency  it was a conversion related issue https://stackoverflow.com/questions/69556088/converting-html-file-to-uint8list-in-flutter
