### ISSUE TITLE
run example is not work: TargetPlatform.macOS is not supported

### ISSUE THREAD

**Issue by songqii** [deakjahn/flutter_dropzone#37]
OS:
macOS (desktop)   • macos            • darwin-arm64   • macOS 11.4 20F71 darwin-arm

![image](https://user-images.githubusercontent.com/5357856/141299235-e22ebbed-6504-42f6-a772-13b2e4704a64.png)

**Comment by deakjahn** [comment]
Considering that this is explicitely a _web-only_ package, is there something we can do about it? :-)
