### ISSUE TITLE
DropzoneView.TargetPlatform.windows is currently not supported

### ISSUE THREAD

**Issue by shareef-dweikat** [deakjahn/flutter_dropzone#38]
Hi
I get this message in my flutter windows app when adding Dropzone
"DropzoneView.TargetPlatform.windows is currently not supported"

Does that mean the package is not supported on windows? If so, is it going to support Windows soon?

**Comment by deakjahn** [comment]
As th README states, this is a "A Flutter **Web** plugin to handle drag-and-drop (files) into Flutter." I might be tempted to look into other platforms later, though...
