### ISSUE TITLE
How about dropping / picking folders?

### ISSUE THREAD

**Issue by Wissperwind** [deakjahn/flutter_dropzone#39]
Hi,

Is it already possible to drop folders?
The effect should be to add all files contained in that folder.
There could be accordingly two buttons. One to pick files, and another one to pick a folder.

**Comment by deakjahn** [comment]
It seems unlikely. Although there is a non-standard extension supported by the majority of browsers, the user has to specifically and manually enable it first to work. I don't think it would really work in an app that way.
