### ISSUE TITLE
BUG | clearFocus is now async

### ISSUE THREAD

**Issue by louisgv** [deakjahn/flutter_dropzone#4]
```
hosted/pub.dartlang.org/flutter_dropzone_web-1.0.5/lib/html_element_view.dart:52:8: Error: The return type of the method '_HtmlElementViewControllerEx.clearFocus' is 'void', which does not match the return type, 'Future<void>', of the overridden method, 'PlatformViewController.clearFocus'.
 - 'Future' is from 'dart:async'.
Change to a subtype of 'Future<void>'.
  void clearFocus() {}
       ^
```

This occurs in the latest Flutter dev `1.20.0-7.1.pre`

**Comment by deakjahn** [comment]
Possible. But I'm not sure it would be wise to follow it until it appears in at least the beta channel. Besides, the whole file should be removed as soon as the bug https://github.com/flutter/flutter/issues/56181 is fixed because it's nothing else but a workaround for missing functionality.

**Comment by deakjahn** [comment]
The time has now come...
