### ISSUE TITLE
Support for other platforms

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [deakjahn/flutter_dropzone#5]
Do you think you might support other platforms in future?

Flutter now officially supports Linux and macOS as desktop platforms. Moreover, on Chrome OS devices, Dual-Screen devices or Multi-Window-Android devices, Android apps are generally capable of handling drop in of files too. It would be great to have support for dropping files on these three platforms too. (About iOS I am not sure but I think it does not handle dropping of files.)

This could be realized using Dart conditional imports like:

```dart
import 'handle_drop_stub.dart'
// ignore: uri_does_not_exist
    if (dart.library.io) 'handle_drop_io.dart'
// ignore: uri_does_not_exist
    if (dart.library.html) 'handle_drop_web.dart';

```

Within the IO-part, you could then make the difference between the different platforms using the following code:

```dart
if (Platform.isAndroid || Platform.isIOS || Platform.isFuchsia) {
    doStuffMobile();
  } else {
    doStuffDesktops();
  }
```

An example how to support Web, Desktop and mobile within one plugin may be found here: https://gitlab.com/testapp-system/file_picker_cross

**Comment by deakjahn** [comment]
As to the first question, I don't know whether those are covered by other drag-drop solutions already mentioned in the README. This one was done specifically to provide something that was missing from them, the web support. Having said that, if there still is a coverage gap, then probably possible.

To the second question, definitely and emphatically **no.** `Flutter_dropzone` is already a [federated plugin](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#federated-plugins). This is the only right way forward to support different platforms, the conditional imports are a relatively poor interim solution that no longer should be used for this.

This also means that anybody (if you're interested? :-) ) can provide support for any new platform of the ones you mention, written in a separate and standalone plugin, and if it's working as it should be, we can just add to this current plugin as the "officially supported" solution for that platform.
