### ISSUE TITLE
Not supported file type should trigger error on file drop

### ISSUE THREAD

**Issue by fralways** [deakjahn/flutter_dropzone#50]
Hello! 

We should have some kind of event when user tries to drop a file which is not in supported file type list, either trough onError callback, or some new callback. Currently, no callback is invoked, and we are unable to show any error message thus user is left thinking that something is not working.

**Comment by fralways** [comment]
Thanx for fast response! Ill reopen in case i see something missing.

**Comment by deakjahn** [comment]
I didn't yet publish it, just uploaded here. Can you check it and confirm? I'll wait with the publishing until then.
