### ISSUE TITLE
Display url image from createFileUrl?

### ISSUE THREAD

**Issue by naveenbharadwaj19** [deakjahn/flutter_dropzone#56]
Hello,
How to display image from the `createFileUrl`? I'm getting a url something like this `blob:http://localhost:63524/dc2ffda9-560b-450c-a38a-25a17ba37ad4` .I'm trying to display that url in networkimage. And what will `releaseFileUrl `do and when to use it?

**Comment by deakjahn** [comment]
It's about the same kind of URL that you use to display an image from the web. So, you can use `Image.network()` or one of the many image loader packages (I had experience with [octo_image](https://pub.dev/packages/octo_image) but there are quite afew like it). You release the URL when you're done with the image. Maybe when you leave the page where it's displayed?

**Comment by naveenbharadwaj19** [comment]
Thanks i was releasing the url right after creating it that's why i couldn't able to display it
