### ISSUE TITLE
Breaks building of iOS app

### ISSUE THREAD

**Issue by ChristianPauly** [deakjahn/flutter_dropzone#6]
I'm creating an app which is used on Android, iOS and the web.

## Expected behaviour:
Dropzone is working on web
On Android and iOS it does nothing

## Current behaviour:
Dropzone is working on web
On Android it does nothing
On iOS this leads to an error and makes it impossible to build the app anymore:
```
username@MacBook-Air ios % pod install              
Analyzing dependencies
[!] No podspec found for `flutter_dropzone` in `.symlinks/plugins/flutter_dropzone/ios`
```

## Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale de)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by deakjahn** [comment]
I already fixed this with another plugin of mine, now which one was that. :-)

**Comment by deakjahn** [comment]
This one. :-) Look at: https://github.com/deakjahn/flutter_dropzone/tree/master/flutter_dropzone_web/ios

Now either you use the previous version of the plugin or there is a new change in the iOS department. The first one is easier to check...

**Comment by deakjahn** [comment]
The main plugin received it, too. Please, confirm it this solved the issue.

**Comment by deakjahn** [comment]
@ChristianPauly The main plugin received it now, too. Please, confirm if this solved the issue.

**Comment by ChristianPauly** [comment]
Yes it is working. Thank you very much!!
