### ISSUE TITLE
onError or onLeave not called when incorrect mime type dropped

### ISSUE THREAD

**Issue by gbmiranda** [deakjahn/flutter_dropzone#66]
Hi,

onLeave or onError is not being called after dropping a file not allowed by the mime type.

Any chance of correction?

**Comment by deakjahn** [comment]
I'm not really sure this would be a good idea, it was never intended that way. MIME types simply restrict the droppable files but don't necessarily mean a hard error. It would certainly be a breaking change if we modified that behavior now...

**Comment by gbmiranda** [comment]
Hi, thanks for the quick response! Your arguments are valid, but we have some situations:

1- the onHover is called for files not accepted and I highlight the zone, if the user tries to add I have no event afterwards to remove the highlight and give a feedback warning that files are not accepted, maybe create a new event called **onDropInvalid** ?
2- another **UX** suggestion, when I place the file above the zone, the cursor shows a green icon, when for an invalid file, it displays a red icon.

I even managed to solve the hover issue by adding a MouseRegion over the zone and controlling it by onEnter / onExite, but I still haven't seen a way to display feedback to the user warning that the file is not accepted.

**Comment by deakjahn** [comment]
@gbmiranda Adding a new callback wasn't that complicated. Please, check it out.

**Comment by gbmiranda** [comment]
Perfect thank you! Will you publish to pub.dev?

**Comment by gbmiranda** [comment]
onDropInvalid event was not called :(

**Comment by deakjahn** [comment]
I tried the example, even left the MIME there for now and it works for me. Did you try that directly?

**Comment by gbmiranda** [comment]
I tried it on my own project, here's a print of the code.

mime: ['image/jpeg', 'image/jpg', 'image/png'];

<img width="615" alt="Captura de Tela 2023-07-28 às 08 24 30" src="https://github.com/deakjahn/flutter_dropzone/assets/8632216/91b9071d-d039-44ce-bebf-df8c34edab25">

When I drop a CSV or ZIP file, the onDropInvalid event does not fire

**Comment by deakjahn** [comment]
Then first, please, try the example, that's the one we have in common...

**Comment by gbmiranda** [comment]
if I download the example and run it, it works, but when I put it in my project with version 3.0.6 it doesn't. Even if I exactly copy your DropZone implementation the onDropInvalid event is not called.

Could it be that something was missing from the uploaded version?

**Comment by deakjahn** [comment]
Strange. All three seem to be upgraded:

* https://pub.dev/packages/flutter_dropzone/versions
* https://pub.dev/packages/flutter_dropzone_platform_interface/versions
* https://pub.dev/packages/flutter_dropzone_web/versions

Do check in your `Pub\Cache\hosted\pub.dev` that you have these versions of all three.

**Comment by deakjahn** [comment]
@gbmiranda I really can't get a handle on this yet. I started a new project, web only. I copied `main.dart` from the plugin example. Here it is packed, I modified nothing else from the standard Flutter project template: 
[untitled.zip](https://github.com/deakjahn/flutter_dropzone/files/12206914/untitled.zip)

And it runs just fine:

![Untitled-1](https://github.com/deakjahn/flutter_dropzone/assets/2234271/fa89b969-cc72-49fe-bb40-994ede25dfa9)

**Comment by deakjahn** [comment]
What you could do is to put a breakpoint here in your browser Dev Tools and see what really happens, step by step:

https://github.com/deakjahn/flutter_dropzone/blob/be7275b4d92c1fdb3e3c4e60a57518dba32d17fa/flutter_dropzone_web/lib/assets/flutter_dropzone.js#L52-L59

**Comment by gbmiranda** [comment]
I'm thinking it's a flutter package caching problem... the file you sent me doesn't have the onDropInvalid handlers

<img width="570" alt="Captura de Tela 2023-07-31 às 10 06 27" src="https://github.com/deakjahn/flutter_dropzone/assets/8632216/3babfc1f-3d92-41cb-b902-69758345d428">

**Comment by gbmiranda** [comment]
For some reason I need to override flutter_dropzone_web to get the right version.

Working now!

<img width="273" alt="Captura de Tela 2023-07-31 às 10 35 10" src="https://github.com/deakjahn/flutter_dropzone/assets/8632216/05b06091-c7d6-4d23-b1e1-6bdfba378dee">

**Comment by deakjahn** [comment]
I didn't yet change it to .10 in the `.yaml`, that's true, but it should work, anyway, this is rather strange. What if you delete all the version folders in the pub cache and run `pub get` again? Do you get version .10 then?

**Comment by gbmiranda** [comment]
takes 3.0.9 and 3.0.10, but for some reason when I build it uses 3.0.9... it only works if I override it.

**Comment by deakjahn** [comment]
Who knows. I advanced the version now here and it will appear in the next published one.
