### ISSUE TITLE
Unnecessary Imports Commit Broke Flutter Application Build - Version 2.8.1

### ISSUE THREAD

**Issue by sommen01** [deakjahn/flutter_dropzone#67]
Hello,

Hope this message finds you well. I'm writing to let you know about an issue with our Flutter app, currently in version 2.8.1. Recently, a commit was made that removed unnecessary imports, specifically 'import 'dart:typed_data'. Unfortunately this led to a broken build on version 2.8.1. 

![image](https://github.com/deakjahn/flutter_dropzone/assets/52509374/ffed9d47-a577-4328-9466-ed5e1d7446bc)

**Comment by deakjahn** [comment]
I don't really understand what that 2.8.1 version number is. The plugin is at 3.0.5, and as far as I can tell, it compiles just fine for me.

**Comment by deakjahn** [comment]
Your what? :-)) Flutter is at 3.10.6 right now...

If what you say above is not a misunderstanding and you're really using such an old SDK that predates anything current in Flutter and Dart (null safety, just to name one) then I'm afraid it will come back the next time around. The toolchain actively warns that I should remove the reference and frankly, I really shouldn't make steps to accommodate 2.x in 2023. :-)
