### ISSUE TITLE
Allow to change cursor type when mouse is over the DropzoneView

### ISSUE THREAD

**Issue by ozz-rjq** [deakjahn/flutter_dropzone#7]
First of all, thanks for the great package, it works great for me. There is also one improvement that would be great to have. In my case I use `DropzoneView` in a `Stack`, with some interactive elements (like buttons) above it. But seems like there is no way to change the type of the mouse cursor when it is over the dropzone (it always shows the default one). I would like to indicate that the buttons are actually clickable (by showing respective cursor). Is it possible to implement such a behaviour?

**Comment by deakjahn** [comment]
The browser shows the usual drop cursor, depending on the actual operation you ask for (like copy, move, link, etc). Is this cursor what you mean?

**Comment by ozz-rjq** [comment]
No, actually I mean not the mouse cursor when you're dropping a file, but when you just hovering over the area with a dropzone view. In that case it always shows the default mouse cursor, but I would like to show the 'hand' cursor to indicate that some element is clickable (for example, a button).

**Comment by deakjahn** [comment]
In my Chrome it actually seems to show the hand, anyway...

**Comment by deakjahn** [comment]
What about this Grab cursor?

**Comment by ozz-rjq** [comment]
I think the issue with this approach is that it always shows one type of a cursor. I was wondering if it's possible to change it dynamically (when hovering over certain elements), for example: 
![dropzone](https://user-images.githubusercontent.com/33256716/90534426-6386d400-e182-11ea-9a00-0d3f791c27dd.png)

**Comment by deakjahn** [comment]
There is an `onHover` event that's called. I can add a new function to the controller, much like the existing `setOperation()` that allows you to set the cursor. But only you can tell whether this is enough for your needs...

**Comment by deakjahn** [comment]
`DropzoneView` now has a `cursor` parameter. The `onHover` approach doesn't seem to work because during the drag hover, the drag operation cursor dictates.

**Comment by ozz-rjq** [comment]
thanks, I will always use the hand cursor for now.

**Comment by deakjahn** [comment]
Does this cover your use case? Because then I can promote the versions on pub.dev.

**Comment by ozz-rjq** [comment]
yes please, thanks.
