### ISSUE TITLE
Not working for web

### ISSUE THREAD

**Issue by Rajuavs** [deakjahn/flutter_dropzone#79]
Getting error as bellow

/pub.dev/flutter_dropzone_web-3.0.13/lib/flutter_dropzone_plugin.dart
    final scriptUrl = html.assetManager.getAssetUrl(
 in the file of flutter_dropzone_plugin.dart
please check and update. my flutter version is: 3.10.5

**Comment by deakjahn** [comment]
> please check and update. my flutter version is: 3.10.5

Please, consider https://github.com/deakjahn/flutter_dropzone/issues/78. Your Flutter version is **almost a year old now.**
