### ISSUE TITLE
flutter dropzone getting error as bellow:

### ISSUE THREAD

**Issue by Rajuavs** [deakjahn/flutter_dropzone#81]
getting error as bellow

`
/C:/Users/HP/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_dropzone_web-3.0.13/lib/flutter_dropzone_plugin.dart:27:8: Error: Undefined name 'platformViewRegistry'.
    ui.platformViewRegistry.registerViewFactory(
       ^^^^^^^^^^^^^^^^^^^^
/C:/Users/HP/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_dropzone_web-3.0.13/lib/flutter_dropzone_plugin.dart:33:26: Error: Undefined name 'assetManager'.
    final scriptUrl = ui.assetManager.getAssetUrl(
`

**Comment by deakjahn** [comment]
See https://github.com/deakjahn/flutter_dropzone/issues/78
