### ISSUE TITLE
FormatException: Invalid Shader Data

### ISSUE THREAD

**Issue by AlehSabadashGmail** [deakjahn/flutter_dropzone#83]
flutter_dropzone: ^4.0.0 does not work on Web

Error: FormatException: Invalid Shader Data
../dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
../lib/_engine/engine/shader_data.dart 24:7                                     fromBytes
../lib/_engine/engine/canvaskit/painting.dart 305:46                            fromBytes
../lib/_engine/engine/canvaskit/renderer.dart 469:32                            <fn>
../dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
../dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
../dart-sdk/lib/async/future_impl.dart 838:44                                   handleValueCallback
../dart-sdk/lib/async/future_impl.dart 867:13                                   _propagateToListeners
../dart-sdk/lib/async/future_impl.dart 643:5                                    [_completeWithValue]
../dart-sdk/lib/async/future_impl.dart 713:7                                    callback
../dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
../dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>

flutter doctor
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.88.1)
[✓] Network resources

  flutter_dropzone: ^3.0.7 works fine with flutter 3.19.6

**Comment by deakjahn** [comment]
Sorry, but this package has even remotely nothing to do with the graphics rendering in the CanvasKit engine.

I can't test on a Mac but I've just tried Edge (Chrome inside) that's built into Windows inevitably, and I experience nothing like that with the bundled example. Do you have the problem with the example or your own web app?
