### ISSUE TITLE
The pickFiles method does not work

### ISSUE THREAD

**Issue by vvp-2020** [deakjahn/flutter_dropzone#84]
flutter_dropzone: ^4.0.0. 

The pickFiles method does not work on Web.

When running the flutter_dropzone\example, I click the "Pick file" button, but the "Open File" dialog box does not open.

flutter doctor
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.19045.4291], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2019 16.11.14)
[!] Android Studio (not installed)
[√] VS Code (version 1.89.0)
[√] Connected device (3 available)
[√] Network resources

**Comment by deakjahn** [comment]
I'm still at loss about why this happens. Safari has some extra handling because why not, why should it be like all the others but it's even more troubling that, as far as I can tell, Edge (and maybe other Chrome engines?) started to claim Safari as well in their UA string. This might mean that were're no longer able to tell them apart this way.

**Comment by deakjahn** [comment]
**Make sure you keep your Flutter up-to-date.**

See https://github.com/deakjahn/flutter_dropzone/pull/88.
