### ISSUE TITLE
v4.0.0 : type 'NativeByteBuffer' is not a subtype of type 'List' in web/packages/flutter_dropzone_web/flutter_dropzone_web.dart.lib.js 236:44 getFileStream

### ISSUE THREAD

**Issue by tototo23** [deakjahn/flutter_dropzone#86]
Hi,
I don't know when it started, but it looks like since I updated my project to Flutter 3.22, dropping a file in web doesn't work anymore.
I'm using chrome version 124.0.6367.210
flutter_dropzone: ^4.0.0
Flutter 3.22.1

It looks like the JS file type changed : it used to return a `Stream<List<int>>`, and now it returns a `minified:ix<List<int>>`
Just using this code : 

```dart 
DropzoneView(
   ...
  onDrop: (dynamic htmlFile) async {
          print('Drop: $htmlFile');
          var stream = controller.getFileStream(htmlFile);
          print('File stream type is : ${stream.runtimeType}');
          ...
   },
   ...
)
```

`getFileStream(htmlFile)` is supposed to return an object typed : Stream<List<int>>. But i checked in runtime :
Displays in the console  : 
```text
Drop: Instance of 'minified:li'
File stream type is : minified:ix<List<int>>
```

It worked very well until I updated to Flutter 3.22, but i don't know if it's the reason...

**Comment by deakjahn** [comment]
Is this in the example inside the package or your own code? The first still looks like OK to me.

**Comment by tototo23** [comment]
Hi @deakjahn it's just a simple use of the package as documented here : https://pub.dev/packages/flutter_dropzone

I use a `DropzoneView` widget, and just display the type of controller.getFileStream(htmlFile).

I'm using library v4.0.4 with Flutter 3.22.1.
I was reading the code, but now i see in the console an other error : 

> Uncaught MissingPluginException(No implementation found for method updated on channel desktop_drop)

So this is probably the source error, i'll try to investigate or see if i'm missing something...

**Comment by tototo23** [comment]
I reverted to flutter_dropzone: 3.0.7 and it works well again. I'll stay with this version for now :)

**Comment by deakjahn** [comment]
It would be better for humanity if you found the error. ;-)) Yes, we moved on to the new HTML support in Flutter and that might still be a moving target. But they urged us to make the change ASAP...

**Comment by tototo23** [comment]
The only errors I had and were able to investigate are : 
- On dart side, the drop event works, BUT instead of receiving the `Stream<List<int>>` expected and specified, I've got a `minified:ix<List<int>>` (printed in console with the code I gave on my 1st Message). At this point it doesnt crash yet, but as soon as I read the stream, my code expects also a  `Stream<List<int>>` so in Flutter side it throws an error `minified:a8p is not a subtype of type List<int>`
- I thought it was the main error : a type that changed
- But then I checked the console in the browser side, and I've seen the error : `Uncaught MissingPluginException(No implementation found for method updated on channel desktop_drop)` ... So, I guess this is the main error, but it's hard to investigate more :/

**Comment by tototo23** [comment]
I've got an update : 
- I didn't test that part when I made the previous release that got the issue with v4.0.0. In release the error was the on I wrote
- I run it again with v4.0.0 in dev mode, the type shown is not the same (not compiled for release yet) : 
  - The call of "controller.getFileStream(htmlFile)" is supposed to return a `Stream<List<int>>` but in dev it resturns a `_ControllerStream<List<int>>`  : "File stream type is : _ControllerStream<List<int>>".. Don't know if it's ok or not, cause i don't see where _ControllerStream comes from.
  - TypeError: Instance of 'NativeByteBuffer': type 'NativeByteBuffer' is not a subtype of type 'List<int>' in web/packages/flutter_dropzone_web/flutter_dropzone_web.dart.lib.js 236:44  getFileStream
  
Hope it helps

**Comment by deakjahn** [comment]
I got a `_ControllerStream` all right but I didn't yet try release, just debug. It should be OK, we don't really care what kind of Stream it is as long as it's a Stream.

"minified" is something only in release, the JS obfuscation step.

**Comment by deakjahn** [comment]
Dear me, this was the same issue as: https://github.com/deakjahn/flutter_dropzone/issues/93

There's a fix now, please, could you check it?
