### ISSUE TITLE
How to get path

### ISSUE THREAD

**Issue by narendra02031997** [deakjahn/flutter_dropzone#9]
How do i get path of dropped file. Tried a lot but didn't found any solution. 

Please reply ASAP.

Thank you

**Comment by deakjahn** [comment]
There is no way. Please, read the REAME file, that's what it's for. :-)

A browser never gives you a real filesystem path and even if it did, it would never allow you to access it, anyway. The browser can give you a temporary URL that you can use to get the file contents but once the user leaves your app, the URL will no longer be available, so don't even bother storing it. If you need the contents of the file, you have to read it and make sure you store it somewhere yourself, using whatever storage solution the browser offers. All available functions are listed in the "Using the controller" section of the README file.
