### ISSUE TITLE
Dropped File Interpreted as String Causing Exception Since Version 4.0.0

### ISSUE THREAD

**Issue by h3imdall** [deakjahn/flutter_dropzone#94]
**Issue Summary**:
With `flutter_dropzone` version 4.0.0, an error occurs when dropping an image from a browser into the `DropzoneView` widget.

**Details**:
Prior to version 4.0.0, up to `flutter_dropzone` version 3.0.7, I had no issues dropping images from a browser into the `DropzoneView` widget.

**Problem**:
Starting with version 4.0.0:
- Dropping an image into the `DropzoneView` widget passes the file as a `String`.
- This issue appears consistently in both Chrome and Firefox.
- The widget throws an exception, which I am unable to catch because the `onDrop` event is not triggered in Flutter.

**Expected Behavior**:
- The `DropzoneView` widget should properly receive and handle the dropped file and pass it to the onDrop event, as it did in previous versions.

**The exception I get since version 4.0.0**
```bash
DartError: TypeError: "https://domain.com/any-image.jpg": type 'String' is not a subtype of
type 'JSObject'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1405:3                              _failedAsCheck
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1383:3                              _generalAsCheckImplementation
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 243:33  _argumentErrors
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 438:22  validateFunctionToJSArgs
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 198:24    _callDartFunctionFast2
assets/packages/flutter_dropzone_web/assets/flutter_dropzone.js 65:43             drop_handler
```

**flutter doctor summary**

```bash
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale de-DE)
    • Flutter version 3.24.3 on channel stable at /Users/philipp/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (7 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
```

**Comment by deakjahn** [comment]
I'm actually on 3.24.4, I don't know if this makes any difference whatsoever, but I can't reproduce this. The current version, 4.0.3 accepts files as before for me. I always try in Edge because I don't use Chrome otherwise and Edge is undeletable, anyway.

**Comment by h3imdall** [comment]
If I drag a file from my computer into the DropzoneView then I have no problems. The error only occurs when I drag an image from a browser into the DropzoneView widget (another Browser) . Unfortunately I can't test it with Edge because I don't use Windows.

What is version 3.24.4? I don't see this version on the version page. 
https://pub.dev/packages/flutter_dropzone/versions

**Comment by deakjahn** [comment]
Oh, I see. I'll try that.

3.24.4 is Flutter's version.

**Comment by deakjahn** [comment]
@h3imdall 

The problem is with this: https://github.com/deakjahn/flutter_dropzone/blob/431dfecf511a0baf1f09a0a210a1cf362cded78d/flutter_dropzone_web/lib/flutter_dropzone_web.dart#L152

When I started, I only thought about dropping files. Later on, users recommended to add dropping strings as well (dropping an image is equivalent to dropping its URL, so this is the same case). We accommodated this by using a dynamically type `onDrop` that can receive both a file and a string. While this worked with the earlier JS support in Flutter, the new one seems to be more stringent in types and I can't see any way to pass dynamically changing types. This probably means that we would need to introduce a second `onDrop` for the strings, apart from the files. This is a radical, breaking change, so I'm not sure what would be the best way forward.

**Comment by deakjahn** [comment]
Thinking about it, a possible way out could be deprecating `onDrop` completely and urging users to use either or both an `onDropFile` and an `onDropString` instead (depending on what they actually need). What do you think?

**Comment by komakur** [comment]
Also since 4.0.0 dropping files from computer also causing the error on Flutter 3.24.3. 

`DartError: TypeError: Instance of 'JSArray<JSObject?>': type 'List<JSObject?>' is not a subtype of type 'List<JSObject>?'

Maybe those problems are related.

**Comment by deakjahn** [comment]
Could well be. I started to investigate this deprecation way, I check that out as well during my tests.

**Comment by deakjahn** [comment]
This turned out to be rather ambitious... Can I count on you trying to test it? :-)

**Comment by komakurae** [comment]
@deakjahn
Can you check your pubspec.yaml? Because I get error
`Because every version of flutter_dropzone from git depends on flutter_dropzone_platform_interface ^2.1.0 which doesn't match any versions, flutter_dropzone from git is forbidden.`
Or maybe I am missing something

**Comment by deakjahn** [comment]
I already changed the version numbers to the expected new ones because the pubspec has local overrides that make this possible. But true, using from GitHub does not. You could simply edit back the version numbers, or even simpler, just unpack the whole zip and reference it locally, temporarily. If it works, I'll publish is, anyway, and the version number changes are OK then. :-)

**Comment by komakurae** [comment]
@deakjahn I added the package locally, and everything works as expected. Thanks

**Comment by h3imdall** [comment]
@deakjahn I tested this commit and it works very well.
https://github.com/deakjahn/flutter_dropzone/commit/11e25b2771fe952aac4a562186ab266b6e32c4a1

I like the change that the onDrop events are now strongly typed even if that means there is a breaking change.

**Comment by deakjahn** [comment]
We'll see how it works out... Published...

**Comment by deakjahn** [comment]
@h3imdall @komakurae Could you come back to this for a moment? We fixed the web side bt this caused problems to another crowd: people who do multi-platform apps, not only running on web. They won't get web drop zone all right but their app needs to be able to build and our new, stricter typing threw a monkey wrench into the engine:

https://github.com/deakjahn/flutter_dropzone/issues/95

I came up with something that seems to still work for the web side, I'm waiting for their input on the non-web side but could you also make sure there's nothing wrong with this approach for you? Ideally, you shouldn't see any change any more but that's exactly what we need to make sure. :-)

**Comment by deakjahn** [comment]
@h3imdall Please, go a bit above that: https://github.com/deakjahn/flutter_dropzone/commits/master/ There were several commits today, this is an ongoing process. :-)

**Comment by komakur** [comment]
@deakjahn The only problem occured for me, is that now older version of this package doesnt work, because flutter_dropzone_platform_interface is overriden.

**Comment by deakjahn** [comment]
@komakur I'm not sure how you set up your environment now but you should only use packages of the same generation. I didn't upgrade anything on pub.dev yet, of course, but if you have the latest copy in a local package, all the submodules, that should be consistent.

**Comment by deakjahn** [comment]
At any rate, the fresh question is now that if both bunch of people agree that the current version caters for both needs (and the other issue now received some confirmation that it does), then I van go on and publish again. It's not ideal to have two breaking changes in quick succession but, well, better to fix it than to leave it broken. :-)

**Comment by deakjahn** [comment]
@komakur Ok, as I can see now, all the problems you mention were with that outdated version, https://github.com/deakjahn/flutter_dropzone/issues/95 is desperately waiting for the solution, so let's cross that bridge now.
