### ISSUE TITLE
flutter_dropzone_platform_interface - 'dart:js_interop_unsafe' is not available on this platform

### ISSUE THREAD

**Issue by jeremy-giles** [deakjahn/flutter_dropzone#95]
Hello, we seem to encounter a regression with the library.
Our builds returns errors of types:

```
../../../../../../../../.pub-cache/hosted/pub.dev/web-1.0.0/lib/src/helpers.dart:24:8: Error: Dart library 'dart:js_interop' is not available on this platform.
import 'dart:js_interop';
       ^
Context: The unavailable library 'dart:js_interop' is imported through these packages:

    package:mobileapp => package:utils => package:flutter_dropzone => package:flutter_dropzone_platform_interface => package:web => dart:js_interop
    ...
```
```
../../../../../../../../.pub-cache/hosted/pub.dev/web-1.0.0/lib/src/helpers.dart:25:8: Error: Dart library 'dart:js_interop_unsafe' is not available on this platform.
import 'dart:js_interop_unsafe';
       ^
Context: The unavailable library 'dart:js_interop_unsafe' is imported through these packages:

    package:mobileapp => package:utils => package:flutter_dropzone => package:flutter_dropzone_platform_interface => package:web => dart:js_interop_unsafe
    package:mobileapp => package:utils => package:flutter_dropzone => package:web => dart:js_interop_unsafe
    package:mobileapp => package:utils => package:flutter_dropzone => package:flutter_dropzone_platform_interface => package:web => dart:js_interop_unsafe
    package:mobileapp => package:utils => package:flutter_dropzone => package:web => dart:js_interop_unsafe
    package:mobileapp => package:utils => package:flutter_dropzone => package:flutter_dropzone_platform_interface => package:web => dart:js_interop_unsafe
    package:mobileapp => package:utils => package:flutter_dropzone => package:web => dart:js_interop_unsafe
    ...
```

For information, `flutter_dropzone` is used in a `utils` package (which contains generic widgets that use `DropzoneView` for example), which is itself used (depends) on a web application and a mobile application.
Currently we also encounter a problem during the mobile build with "not available on this platform". This was not the case before and we could build our different applications.

Flutter 3.24.3 • channel stable • 
Tools • Dart 3.5.3 • DevTools 2.37.3

**Comment by deakjahn** [comment]
I'm not sure how we can solve this. `flutter_dropzone` is, explicitly, a web package and doesn't want to offer more than that. The recent changes towards the new Flutter web infrastructure were not really my own decision, Flutter itself very vehemently pushes us to move on from the earlier web support to the new one. I'm not even sure which of these changes led to your regression because depending on `web` isn't new in the version at all. So, if someone can come up with a suggestion that solves this, I'm all ears but right now, I have no idea even where to start...

**Comment by Joaojuby** [comment]
Temporarily fixed it for me by overriding dependencies on pubspec.yaml :S looking for an alternative

```
dependency_overrides:
  flutter_dropzone_platform_interface: 2.0.6
  flutter_dropzone_web: 4.0.2
```

**Comment by deakjahn** [comment]
OK, then I think I have a suspicion. It must be that fact that `onDropXXX` became strongly typed, no more `dynamic`, so `onDropFile` has a `web.File` argument now. We can't undo that, obviously, not only because this is "more elegant so" but it actually harmed the primary use case of the package: https://github.com/deakjahn/flutter_dropzone/issues/93

Considering that I don't use it for non-web purposes myself, could any of you come up with either a small repo that can recreate the issue or, even better :-), with a ready-made solution in a PR?

**Comment by deakjahn** [comment]
@nicolasaglianoos Let's do it that way: I'll add a `DropzoneFile` now and make sure that it still works OK in a web scenario. Could you come up with a small repo in the meantime that makes it possible to test in your scenario?

**Comment by deakjahn** [comment]
The interface no longer uses `web` but the submodule still does in `dropzone_file`. That would be the next step somehow.

**Comment by hatemragab** [comment]
Hello i face the same problem 
```
../../.pub-cache/hosted/pub.dev/web-1.1.0/lib/src/helpers/cross_origin.dart:98:5: Error: 'JSArray' isn't a type.
    JSArray<JSObject>? transfer,
    ^^^^^^^
../../.pub-cache/hosted/pub.dev/web-1.1.0/lib/src/helpers/cross_origin.dart:132:25: Error: 'JSAny' isn't a type.
  CrossOriginLocation._(JSAny? o) : _location = _CrossOriginLocation(o);
                        ^^^^^
../../.pub-cache/hosted/pub.dev/web-1.1.0/lib/src/helpers/cross_origin.dart:134:39: Error: 'JSAny' isn't a type.
  static CrossOriginLocation? _create(JSAny? o) {
                                      ^^^^^
../../.pub-cache/hosted/pub.dev/web-1.1.0/lib/src/helpers/events/providers.dart:615:25: Error: 'JSObject' isn't a type.
  final jsObject = e as JSObject;
                        ^^^^^^^^
../../.pub-cache/hosted/pub.dev/web-1.1.0/lib/src/helpers/events/providers.dart:618:47: Error: The getter 'toJS' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'toJS'.
  } else if (jsObject.hasProperty('mozHidden'.toJS).toDart) {
                                              ^^^^
../../.pub-cache/hosted/pub.dev/web-1.1.0/lib/src/helpers/events/providers.dart:620:46: Error: The getter 'toJS' isn't defined for the class 'String'.
```
it took alot of time about 3 days to discover it !!
please help to fix this

**Comment by deakjahn** [comment]
OK, good news, we'll see if the web part is still OK and then I can upgrade.

**Comment by erpanxulu** [comment]
I hope it can be fixed, thank you

**Comment by deakjahn** [comment]
@nicolasaglianoos I was waiting for some green light at https://github.com/deakjahn/flutter_dropzone/issues/94, too, I didn't want to make yet another change that breaks something for some people. :-) If you think we can take chances, I'm game.

**Comment by deakjahn** [comment]
Let's keep our fingers crossed...

**Comment by nicolasaglianoos** [comment]
@deakjahn i have update the project with the last version, web and test works correct

**Comment by deakjahn** [comment]
Thanks. Let's hope it does so for everybody involved. :-)

**Comment by jeremy-giles** [comment]
Hello and thank you for your reactivity.
We're also waiting for a new version to make the feature available again.
For now we have chosen to use the `dependency_overrides` method.

Thanks again for the work and communication.
