### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by Zeroupper** [deakjahn/flutter_dropzone#97]
## [Example](https://pub.dev/packages/flutter_dropzone):

```
import 'package:flutter_dropzone/flutter_dropzone.dart';
...
DropzoneView(
  operation: DragOperation.copy,
  cursor: CursorType.grab,
  onCreated: (DropzoneViewController ctrl) => controller = ctrl,
  onLoaded: () => print('Zone loaded'),
  onError: (String? ev) => print('Error: $ev'),
  onHover: () => print('Zone hovered'),
  onDropFile: (DropzoneFile file) => print('Drop: ${file.webFile}'),
  onDropString: (String s) => print('Drop: $s'),
  onDropFiles: (List<DropzoneFile> files) => print('Drop multiple: $files'),
  onDropStrings: (List<String> strings) => print('Drop multiple: $strings'),
  onLeave: () => print('Zone left'),
);
```
## Error
It seems like types are not correctly imported. I get the following error: 
_Undefined class 'DropzoneInterface'.
Try changing the name to the name of an existing class, or creating a class with the name 'DropzoneInterface'.
Undefined class 'DropzoneFile'.
Try changing the name to the name of an existing class, or creating a class with the name 'DropzoneFile'.
The name 'DropzoneFile' isn't a type, so it can't be used as a type argument.
Try correcting the name to an existing type, or defining a type named 'DropzoneFile'._

## Env
flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-DK)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.90.2)
[✓] Connected device (4 available)
[✓] Network resources
```

I am using `flutter_dropzone: ^4.2.0`

**Comment by deakjahn** [comment]
`DropzoneFileInterface`. The README is probably lagging behind, I'll check it out.

**Comment by deakjahn** [comment]
Yes, you're right. The actual example code, unlike the README, doesn't specify the type, it just uses `onDropFile: (file) {}`. I'll fix this.
